import { AdversarialReport } from './AdversarialTestRunner';

export class AdversarialReportGenerator {
    static generateMarkdownReport(report: AdversarialReport): string {
        const passRate = ((report.passed / report.totalTests) * 100).toFixed(1);

        let md = `# Adversarial Robustness Report
**Date:** ${report.timestamp.toISOString().split('T')[0]}
**Policy Pack:** ${report.policyPackId}
**Total Tests:** ${report.totalTests}
**Pass Rate:** ${passRate}% (${report.passed} passed, ${report.failed} failed)

## Test Results

| ID | Category | Prompt | Expected | Outcome | Details |
|----|----------|--------|----------|---------|---------|
`;

        for (const res of report.results) {
            // Truncate prompt for table
            const prompt = res.prompt.length > 50 ? res.prompt.substring(0, 47) + '...' : res.prompt;
            const emoji = res.outcome === 'PASS' ? '✅' : '❌';

            md += `| ${res.testCaseId} | - | ${prompt.replace(/\|/g, '\\|')} | - | ${emoji} ${res.outcome} | ${res.details} |\n`;
        }

        md += `\n\n*Generated by ConvoGuard AI Adversarial Testing Framework*`;
        return md;
    }
}
